// flow-typed signature: 52b53dc69d2c76fa9c6de795ea032239
// flow-typed version: <<STUB>>/@types/react_v^18.3.3/flow_v0.243.0
// @flow
/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
	declare module.exports: any;
}
