// flow-typed signature: d9404dbf30226743440f3bf1e4b6f51c
// flow-typed version: <<STUB>>/@types/react_v^18.3.11/flow_v0.248.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
