// flow-typed signature: 2563279c06c859bc00d820e8c3ec5ba0
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^12.0.2/flow_v0.245.2
// @flow

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/dist' {
	declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils' {
	declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/dist/index' {
	declare module.exports: $Exports<'copy-webpack-plugin/dist'>;
}
declare module 'copy-webpack-plugin/dist/index.js' {
	declare module.exports: $Exports<'copy-webpack-plugin/dist'>;
}
declare module 'copy-webpack-plugin/dist/utils.js' {
	declare module.exports: $Exports<'copy-webpack-plugin/dist/utils'>;
}
