// flow-typed signature: 8541618f393daba6f1b16bf72043b106
// flow-typed version: <<STUB>>/react-sortablejs_v^6.1.4/flow_v0.248.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortablejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortablejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sortablejs/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sortablejs/dist/index' {
  declare module.exports: $Exports<'react-sortablejs/dist'>;
}
declare module 'react-sortablejs/dist/index.js' {
  declare module.exports: $Exports<'react-sortablejs/dist'>;
}
