// flow-typed signature: 1cc9d57090108326f2ac13e0d7a8da42
// flow-typed version: <<STUB>>/react-sortablejs_v6.1.4/flow_v0.238.0
// @flow
/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortablejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortablejs' {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sortablejs/dist' {
	declare module.exports: any;
}

// Filename aliases
declare module 'react-sortablejs/dist/index' {
	declare module.exports: $Exports<'react-sortablejs/dist'>;
}
declare module 'react-sortablejs/dist/index.js' {
	declare module.exports: $Exports<'react-sortablejs/dist'>;
}
