// flow-typed signature: a218bcb441760d11787c3e539c1d04bc
// flow-typed version: <<STUB>>/scss-reset_v^1.4.2/flow_v0.248.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scss-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scss-reset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scss-reset/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scss-reset/gulpfile.js' {
  declare module.exports: $Exports<'scss-reset/gulpfile'>;
}
