// flow-typed signature: 9dc5db707d520145fcb8d82a8bac0749
// flow-typed version: <<STUB>>/styled-reset_v^4.5.2/flow_v0.245.2
// @flow

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-reset' {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-reset/lib/esm' {
	declare module.exports: any;
}

declare module 'styled-reset/lib' {
	declare module.exports: any;
}

// Filename aliases
declare module 'styled-reset/lib/esm/index' {
	declare module.exports: $Exports<'styled-reset/lib/esm'>;
}
declare module 'styled-reset/lib/esm/index.js' {
	declare module.exports: $Exports<'styled-reset/lib/esm'>;
}
declare module 'styled-reset/lib/index' {
	declare module.exports: $Exports<'styled-reset/lib'>;
}
declare module 'styled-reset/lib/index.js' {
	declare module.exports: $Exports<'styled-reset/lib'>;
}
