export const searchListData = [
	{
		id: 1,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 2,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'Enhance efficiency' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 3,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 4,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 5,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 6,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 7,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 8,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 9,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
	{
		id: 10,
		dataSearch: [
			{ id: 1, text: 'Lorem' },
			{ id: 2, text: 'About us' },
			{ id: 3, text: 'Contacts' },
			{ id: 4, text: 'Flow type checker' },
			{ id: 5, text: 'TypeScript' },
			{ id: 6, text: 'JavaScript' },
			{ id: 7, text: 'learn react' },
			{ id: 8, text: 'GitHub API' },
			{ id: 9, text: 'UI/UX' },
			{ id: 10, text: 'Ant Design' },
			{ id: 11, text: 'Chakra UI' },
			{ id: 12, text: 'Material UI' },
			{ id: 13, text: 'Yandex dzen' },
			{ id: 14, text: 'How to change background on web site' },
			{ id: 15, text: 'Custom hooks ReactJS' },
			{ id: 16, text: 'What is a label in UX design' },
			{ id: 17, text: 'Goals of labels in UX design' },
			{ id: 18, text: 'What is Typescript?' },
			{ id: 19, text: 'Static Typing' },
			{ id: 20, text: 'Type Assertions' },
			{ id: 21, text: 'Primitive Types' },
		],
		dataSearchUsers: [
			{
				id: 1,
				role: 'Creator',
				username: 'Roman Smit',
			},
			{
				id: 2,
				role: 'Assigned',
				username: 'John Doe',
			},
			{
				id: 3,
				role: 'Watcher',
				username: 'Jerrard Doe',
			},
		],
	},
];
